version: "3"

services:
  client:
    build: ./client
    container_name: react_ui
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - server
    networks:
      - mern-network

  server: 
    build: ./server
    container_name: node-api
    restart: always
    ports:
      - "8080:8080"
    networks:
      - mern-network

networks:
  mern-network:
